In [1]:
#Datatypes#Dataty 
#Integers and floating numbers, basic arithmetic operations
eip = 3
print(type(eip)) # Prints "<class 'int'>"
print(eip)       # Prints "3"
print(eip + 1)   # Addition; prints "4"
print(eip - 1)   # Subtraction; prints "2"
print(eip * 2)   # Multiplication; prints "6"
print(eip ** 2)  # Exponentiation; prints "9"
eip += 1
print(eip)  # Prints "4"
eip *= 2
print(eip)  # Prints "8"
mlblr = 2.5
print(type(mlblr)) # Prints "<class 'float'>"
print(mlblr, mlblr + 1, mlblr * 2, mlblr ** 2) # Prints "2.5 3.5 5.0 6.25"

<class 'int'>
3
4
2
6
9
4
8
<class 'float'>
2.5 3.5 5.0 6.25


In [2]:
#Boolean operations
eip = True
mlblr = False
print(type(eip)) # Prints "<class 'bool'>"
print(eip and mlblr) # Logical AND; prints "False"
print(eip or mlblr)  # Logical OR; prints "True"
print(not eip)   # Logical NOT; prints "False"
print(eip != mlblr)  # Logical XOR; prints "True"

<class 'bool'>
False
True
False
True


In [3]:
# Python strings
eip = 'hello'    # String literals can use single quotes
mlblr = "world"    # or double quotes; it does not matter.
print(eip)       # Prints "hello"
print(len(eip))  # String length; prints "5"
eip_in = eip + ' ' + mlblr  # String concatenation
print(eip_in)  # prints "hello world"
eip_out = '%s %s %d' % (eip, mlblr, 2018)  # sprintf style string formatting
print(eip_out)  # prints "hello world 2018"

# methods which can be applied for strings

mlblr_in = "hello"
print(mlblr_in.capitalize())  # Capitalize a string; prints "Hello"
print(mlblr_in.upper())       # Convert a string to uppercase; prints "HELLO"
print(mlblr_in.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(mlblr_in.center(7))     # Center a string, padding with spaces; prints " hello "
print(mlblr_in.replace('l', '(ell)'))  # Replace all instances of one substring with another; # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

hello
5
hello world
hello world 2018
Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


In [4]:
#Containersa in Python
#List
eip_list = [3, 1, 2]    # Create a list
print(eip_list, eip_list[2])  # Prints "[3, 1, 2] 2"
print(eip_list[-1])     # Negative indices count from the end of the list; prints "2"
eip_list[2] = 'foo'     # Lists can contain elements of different types
print(eip_list)         # Prints "[3, 1, 'foo']"
eip_list.append('bar')  # Add a new element to the end of the list
print(eip_list)         # Prints "[3, 1, 'foo', 'bar']"
eip = eip_list.pop()      # Remove and return the last element of the list
print(eip, eip_list)      # Prints "bar [3, 1, 'foo']"

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


In [5]:
#Slicing 

mlblr = list(range(5))     # range is a built-in function that creates a list of integers
print(mlblr)               # Prints "[0, 1, 2, 3, 4]"
print(mlblr[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(mlblr[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(mlblr[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(mlblr[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(mlblr[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
mlblr[2:4] = [8, 9]        # Assign a new sublist to a slice
print(mlblr)               # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


In [6]:
#Loops

eip_list = ['cat', 'dog', 'monkey']
for eip in eip_list:
    print(eip)
# Prints "cat", "dog", "monkey", each on its own line.

#Enumerate

eip_out = ['cat', 'dog', 'monkey']
for mlblr, eip in enumerate(eip_out):
    print('#%d: %s' % (mlblr + 1, eip))
# Prints "#1: cat", "#2: dog", "#3: monkey", each on its own line

cat
dog
monkey
#1: cat
#2: dog
#3: monkey


In [7]:
#List Comprehension

eip_list = [0, 1, 2, 3, 4]
eip = []
for eip_in in eip_list:
    eip.append(eip_in ** 2)
print(eip)   # Prints [0, 1, 4, 9, 16]

eip_list = [0, 1, 2, 3, 4]
eip_out = [eip_in ** 2 for eip_in in eip_list]
print(eip_out)   # Prints [0, 1, 4, 9, 16]

# list comprehensions can also contain conditions

eip_list = [0, 1, 2, 3, 4]
eip_out = [eip_in ** 2 for eip_in in eip_list if eip_in % 2 == 0]
print(eip_out)  # Prints "[0, 4, 16]"

[0, 1, 4, 9, 16]
[0, 1, 4, 9, 16]
[0, 4, 16]


In [8]:

#Dictionaries#Diction 

eip_dict = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(eip_dict['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in eip_dict)     # Check if a dictionary has a given key; prints "True"
eip_dict['fish'] = 'wet'     # Set an entry in a dictionary
print(eip_dict['fish'])      # Prints "wet"
# print(eip_dict['monkey'])  # KeyError: 'monkey' not a key of d
print(eip_dict.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(eip_dict.get('fish', 'N/A'))    # Get an element with a default; prints "wet"
del eip_dict['fish']         # Remove an element from a dictionary
print(eip_dict.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"


# It is easy to iterate over the keys in a dictionary

eip_dict = {'person': 2, 'cat': 4, 'spider': 8}
for eip_in in eip_dict:
    eip_out = eip_dict[eip_in]
    print('A %s has %d legs' % (eip_in, eip_out))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

cute
True
wet
N/A
wet
N/A
A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [9]:
#Dictionary Comprehension

# If you want access to keys and their corresponding values, use the items method:

eip_dict = {'person': 2, 'cat': 4, 'spider': 8}
for eip_in, eip_out in eip_dict.items():
    print('A %s has %d legs' % (eip_in, eip_out))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

# Dictionary comprehension

eip_dict = [0, 1, 2, 3, 4]
eip_out = {eip_in: eip_in ** 2 for eip_in in eip_dict if eip_in % 2 == 0}
print(eip_out)  # Prints "{0: 0, 2: 4, 4: 16}"

A person has 2 legs
A cat has 4 legs
A spider has 8 legs
{0: 0, 2: 4, 4: 16}


In [10]:

#Sets#Sets

  eip_listeip_list = {'cat', 'dog'}
print('cat' in eip_list)   # Check if an element is in a set; prints "True"
print('fish' in eip_list)  # prints "False"
eip_list.add('fish')       # Add an element to a set
print('fish' in eip_list)  # Prints "True"
print(len(eip_list))       # Number of elements in a set; prints "3"
eip_list.add('cat')        # Adding an element that is already in the set does nothing
print(len(eip_list))       # Prints "3"
eip_list.remove('cat')     # Remove an element from a set
print(len(eip_list))       # Prints "2"

IndentationError: unexpected indent (<ipython-input-10-bf7a4e5fb00a>, line 4)

In [11]:

#Sets#Sets

eip_listeip_list = {'cat', 'dog'}
print('cat' in eip_list)   # Check if an element is in a set; prints "True"
print('fish' in eip_list)  # prints "False"
eip_list.add('fish')       # Add an element to a set
print('fish' in eip_list)  # Prints "True"
print(len(eip_list))       # Number of elements in a set; prints "3"
eip_list.add('cat')        # Adding an element that is already in the set does nothing
print(len(eip_list))       # Prints "3"
eip_list.remove('cat')     # Remove an element from a set
print(len(eip_list))       # Prints "2"

False
False


AttributeError: 'list' object has no attribute 'add'

In [12]:
#Sets

eip_list = {'cat', 'dog'}
print('cat' in eip_list)   # Check if an element is in a set; prints "True"
print('fish' in eip_list)  # prints "False"
eip_list.add('fish')       # Add an element to a set
print('fish' in eip_list)  # Prints "True"
print(len(eip_list))       # Number of elements in a set; prints "3"
eip_list.add('cat')        # Adding an element that is already in the set does nothing
print(len(eip_list))       # Prints "3"
eip_list.remove('cat')     # Remove an element from a set
print(len(eip_list))       # Prints "2"

True
False
True
3
3
2


In [13]:
#Tuples

eip_dict = {(eip, eip + 1): eip for eip in range(10)}  # Create a dictionary with tuple keys
mlblr = (5, 6)        # Create a tuple
print(type(mlblr))    # Prints "<class 'tuple'>"
print(eip_dict[mlblr])       # Prints "5"
print(eip_dict[(1, 2)])  # Prints "1"


<class 'tuple'>
5
1


In [14]:
#Functions

def sign(eip):
    if eip > 0:
        return 'positive'
    elif eip < 0:
        return 'negative'
    else:
        return 'zero'

for eip in [-1, 0, 1]:
    print(sign(eip))
# Prints "negative", "zero", "positive"

negative
zero
positive


In [15]:

#Function Arguments#Functio 

def hello(eip, mlblr=False):
    if mlblr:
        print('HELLO, %s!' % eip.upper())
    else:
        print('Hello, %s' % eip)

hello('Bob') # Prints "Hello, Bob"
hello('Fred', mlblr=True)  

Hello, Bob
HELLO, FRED!


In [16]:
#NumPy

import numpy as eip

mlblr = eip.array([1, 2, 3])   # Create a rank 1 array
print(type(mlblr))            # Prints "<class 'numpy.ndarray'>"
print(mlblr.shape)            # Prints "(3,)"
print(mlblr[0], mlblr[1], mlblr[2])   # Prints "1 2 3"
mlblr[0] = 5                  # Change an element of the array
print(mlblr)                  # Prints "[5, 2, 3]"

mlblr = eip.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(mlblr.shape)                     # Prints "(2, 3)"
print(mlblr[0, 0], mlblr[0, 1], mlblr[1, 0])  

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [17]:
#Some NumPy Functions

import numpy as eip

eip_in = eip.zeros((2,2))   # Create an array of all zeros
print(eip_in)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

eip_in = eip.ones((1,2))    # Create an array of all ones
print(eip_in)              # Prints "[[ 1.  1.]]"

eip_in = eip.full((2,2), 7)  # Create a constant array
print(eip_in)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

eip_in = eip.random.random((2,2))  # Create an array filled with random values
print(eip_in)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[0.95036291 0.38216656]
 [0.39083613 0.69056387]]


In [18]:
#Mixing integer indexing with slice indexing

import numpy as eip

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
mlblr = eip.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
eip_in = mlblr[1, :]    # Rank 1 view of the second row of a
eip_out = mlblr[1:2, :]  # Rank 2 view of the second row of a
print(eip_in, eip_in.shape)  # Prints "[5 6 7 8] (4,)"
print(eip_out, eip_out.shape)  # Prints "[[5 6 7 8]] (1, 4)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [19]:

#Datatypes#Datatyp 

import numpy as eip

eip_in = eip.array([1, 2])   # Let numpy choose the datatype
print(eip_in.dtype)         # Prints "int64"

eip_in = eip.array([1.0, 2.0])   # Let numpy choose the datatype
print(eip_in.dtype)             # Prints "float64"

eip_in = eip.array([1, 2], dtype=eip.int64)   # Force a particular datatype
print(eip_in.dtype)                         # Prints "int64"

int32
float64
int64


In [20]:

#Array Math#Array M 

import numpy as eip

eip_in = eip.array([[1,2],[3,4]], dtype=eip.float64)
eip_out = eip.array([[5,6],[7,8]], dtype=eip.float64)

print(eip.add(eip_in, eip_out)) 
# [[ 6.0  8.0]
#  [10.0 12.0]]

print(eip.subtract(eip_in, eip_out)) or print(eip_in - eip_out)
# [[-4.0 -4.0]
#  [-4.0 -4.0]]

print(eip.multiply(eip_in, eip_out)) or print(eip_in * eip_out)
# [[ 5.0 12.0]
#  [21.0 32.0]]

print(eip.divide(eip_in, eip_out)) or print(eip_in / eip_out)
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]

print(eip.sqrt(eip_in))
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]

[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [21]:

#Dot function#Dot fun 

import numpy as eip

eip_in = eip.array([[1,2],[3,4]])
eip_out = eip.array([[5,6],[7,8]])

mlblr_in = eip.array([9,10])
mlblr_out = eip.array([11, 12])

# Inner product of vectors; both produce 219
print(mlblr_in.dot(mlblr_out))
print(eip.dot(mlblr_in, mlblr_out))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(eip_in.dot(mlblr_in))
print(eip.dot(eip_in,mlblr_in))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(eip_in.dot(mlblr_in))
print(eip.dot(eip_in, mlblr_in))

219
219
[29 67]
[29 67]
[29 67]
[29 67]


In [22]:

#Sum along an axis#Sum alo 

import numpy as eip

eip_in = eip.array([[1,2],[3,4]])

print(eip.sum(eip_in))  # Compute sum of all elements; prints "10"
print(eip.sum(eip_in, axis=0))  # Compute sum of each column; prints "[4 6]"
print(eip.sum(eip_in, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [23]:
#MathPlotLib - Plotting Graphs

import numpy as eip
import matplotlib.pyplot as mlblr

# Compute the x and y coordinates for points on a sine curve
eip_in = eip.arange(0, 3 * eip.pi, 0.1)
eip_out = eip.sin(eip_in)

# Plot the points using matplotlib
mlblr.plot(eip_in, eip_out)
mlblr.show()  # You must call plt.show() to make graphics appear.

<Figure size 640x480 with 1 Axes>